### your site title here

title: Vitor Baldoino
description: Data Scientist | Economist

baseurl: ""
url: "https://baldoinov.github.io"
email: "vdbaldoino@gmail.com"

# Pagination
paginate: 4
permalink: /blog/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "baldoinov/"
github: "baldoinov"
orcid: "0009-0007-5746-1819"
# researchgate: "#"
# stackoverflow: "#"
# twitter: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - ImpactoGastoPublico.md
      - impactoUPAsSP.md


sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: "{{reference}}"
  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details
  query: "@*"